<?php

namespace conerd\humhub\modules\geolocation;

use conerd\humhub\modules\geolocation\migration\Uninstall;
use conerd\humhub\modules\geolocation\migration\Enable;
use humhub\modules\user\models\Group;
use Yii;
use yii\helpers\Url;

class Module extends \humhub\components\Module
{

    /**
     * @var string sort field (e.g. lastname) of member list (leave empty to sort by auto sort search)
     */
    public $memberListSortField = '';

    /**
     * @var int default page size for directory pages
     */
    public $pageSize = 25;

    /**
     * @var bool defines if the directory is active, if not the directory is not visible and can't be accessed
     */
    public $active = true;

    /**
     * @var bool defines if the directory is available for guest users, this flag will only have effect if guest access is allowed and the module is active
     */
    public $guestAccess = false;

    /**
    * @inheritdoc
    */
    public function getConfigUrl()
    {
        return Url::to(['/geolocation/admin']);
    }

    /**
    * @inheritdoc
    */
    public function disable()
    {
        $uninstall = new Uninstall();
        $uninstall->up();
        // Cleanup all module data, don't remove the parent::disable()!!!
        parent::disable();
    }

    public function enable()
    {
        $enable = new Enable();
        $enable->safeUp();
        return parent::enable(); // TODO: Change the autogenerated stub
    }

    /**
     * Show groups in directory
     *
     * @return boolean
     */
    public function isGroupListingEnabled()
    {
        return (Group::find()->where(['show_at_directory' => 1])->count() != 0);
    }

    public function getPath(){
        return "protected/modules/geolocation";
    }

}
